### ISSUE TITLE
Feature request: shell-commando 'resultaat' voor overzicht resultaatrekeningen

### ISSUE THREAD

**Issue by ghost** [eekboek/eekboek#1]
Feature request:
Is het een idee of ooit eens overwogen om het overzicht 'result' een alias 'resultaat' of 'resultaten' mee te geven?

'Result' is een van de weinige engelse termen die worden gehanteerd binnen ebshell (eekboek-master/lib/EB/Shell/Base.pm) en daarmee zou de consistentie worden verhoogd. Alleen een alias zou voldoende zijn, want dan is de impact op de zelf-test / ivp minder groot.

**Comment by sciurius** [comment]
Goede suggestie. Ik heb 'resultaat' het primaire commando gemaakt en 'result' de alias.
