### ISSUE TITLE
Patch: leesbaarheid, spelfout van relaties.eb

### ISSUE THREAD

**Issue by ghost** [eekboek/eekboek#2]
Een `diff -u` van relaties.eb uit de voorbeeldadministratie:
- spelfout
- leesbaarheid, waaronder commentaar

[relaties.diff.gz](https://github.com/eekboek/eekboek/files/8986911/relaties.diff.gz)

**Comment by sciurius** [comment]
Dank.

Tip: Als je dit soort wijzigingsvoorstellen als een PR doet krijg je eeuwige roem ☺.
