### ISSUE TITLE
Feature request: check_version

### ISSUE THREAD

**Issue by ghost** [eekboek/eekboek#3]
Is het een idee om `ebshell --version` en/of `ebshell -v` te definieren en deze een Perl aanroep te laten doen naar `check_version.pl`? Ik verwacht dat de meesten ebshell opstarten om te zien welke versie zij draaien, maar het zou mooier zijn ook deze optie te hebben.

**Comment by sciurius** [comment]
eshell kent de `--version` optie, maar behandelt deze als `--ident`. Naar 'goed gebruik' zou het enkel de versie moeten laten zien en dan stoppen. Je zou dat even op de mailing list moeten zetten om te vragen of mensen daar last van zouden hebben.

Wat je bedoelt met `check_version.pl` weet ik niet. Kun je dat verduidelijken?

**Comment by ghost** [comment]
In eekboek-master wordt een aanroep gedaan naar een subroutine check_version (underscore): `grep -nr check_version .` Er is echter een Perl file genaamd check-version.pl (streepje). Een van de twee zou gebruikt kunnen worden voor `ebshell --version` zonder de EekBoek shell ook echt te launchen.
Ik kijk nog wel hoe ik lid kan worden van de mailinglijst, onlangs was het mij niet gelukt.

**Comment by sciurius** [comment]
Ok, ik denk dat ik het snap.
Het filetje `check-version.pl` is een overblijfsel van vroeger, een test progje dat per ongeluk in de git is terecht gekomen. Ik zal het verwijderen.
De subroutine `check_version` die je in ebshell aantreft verifieert dat bepaalde critische componenten er zijn en van de juiste versie zijn. Dat heeft totaal geen relatie met `ebshell --version`.
Als je per se de versie wilt tonen zonder de ebshell op te starten: `perl lib/EB/Version.pm`. Maar denk je dat dat nuttig is?

**Comment by ghost** [comment]
Dat laatste helpt inderdaad. Voor regelgeving, maar ook interne rapportage, is het wel eens nodig dat een lijst van alle programmatuur, wat deze doet, welke licentie, type dataverwerking en ook het bijbehorende versienummer wordt overgedragen. Dan zou het het fijn zijn als alles gescript kan worden gedaan met een uniforme code, in casu `--version`.

**Comment by sciurius** [comment]
Zoals gezegd, `--version` wordt reeds ondersteund. Ik zal aanpassen dat de ebshell daarna stopt.
